source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.0'

target 'AppController_Example' do
  pod "AppController", :path => "../"
end

target 'AppController_Tests' do
  pod "AppController", :path => "../"  
end
